import Theme from '../theme-provider'
import { Caveat, Inter } from 'next/font/google'
import localFont from 'next/font/local'

import QuoteTitle from '@/components/quote-title'
import Header from '@/components/ui/header'

import './css/style.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const caveat = Caveat({
  subsets: ['latin'],
  variable: '--font-caveat',
  display: 'swap',
})

const orbiter = localFont({
  src: [
    {
      path: '../public/fonts/OrbiterDisplay-Bold.woff',
      weight: '700',
    },
  ],
  variable: '--font-orbiter',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      {/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body
        className={`${inter.variable} ${caveat.variable} ${orbiter.variable} font-inter bg-white tracking-tight text-slate-800 antialiased dark:bg-slate-950 dark:text-slate-200`}>
        <Theme>
          <div className='flex min-h-screen flex-col overflow-hidden'>
            <Header />

            <div className='flex grow flex-col lg:flex-row'>
              {/* Left side */}
              <QuoteTitle title='The Markyk Corp.' date='20 April, 2024' />

              {/* Right side */}
              <main className='flex w-full flex-col max-lg:grow lg:ml-auto lg:w-1/2'>
                {children}
              </main>
            </div>
          </div>
        </Theme>
      </body>
    </html>
  )
}
